In [46]:
paisa = int(input("Enter the paisa amount"))
rupees = paisa // 100
paisa = paisa % 100
print(rupees," Rupees and",paisa," Paisa")
if rupees % 5 == 0:
    print("Only 5 & 10 Rupee Notes Possible: Yes")
else:
    print("Only 5 & 10 Rupee Notes Possible: No")

10  Rupees and 89  Paisa
Only 5 & 10 Rupee Notes Possible: Yes


2. Control Structures
Given an integer n, print all numbers from 1 to n that are either palindrome or Armstrong numbers. Also
count how many numbers satisfy both conditions. Sample Input:
200
Sample Output:
Palindrome or Armstrong Numbers: 1 2 3 4 5 6 7 8 9 11 22 33 44 55 66 77 88 99 101 121 131 153
Count satisfying both: 10

In [38]:
def palindrome(n):
    st = str(n)
    return st == st[::-1]

def armstrong(n):
    temp = n
    size = len(str(n))
    s = 0

    while temp > 0:
        r = temp % 10
        s += r ** size
        temp //= 10

    return s == n

n = int(input("Enter the range: "))

palorarm = []
both = []

for i in range(1, n):
    if(i<10):
        palorarm.append(i)
    if palindrome(i) and armstrong(i):
        both.append(i)
    elif palindrome(i) or armstrong(i):
        palorarm.append(i)

print("Palindrome or Armstrong Numbers:", palorarm)
print("Count satisfying both:", len(both))


Palindrome or Armstrong Numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33, 44]
Count satisfying both: 9


In [39]:
def factors(n):
    count = 0
    sum = 0

    for i in range(1, n + 1):
        if n % i == 0:
            count += 1
            sum += i

    if sum == 2 * n :
        perfect = "Yes"
    else:
        perfect = "No"

    return count, sum, perfect

n = int(input("Enter a number: "))
count, total, perfect = factors(n)

print("Factors:", count)
print("Sum:", total)
print("Perfect Number:", perfect)


Factors: 6
Sum: 56
Perfect Number: Yes


Using recursion, count how many zeros are present in a given integer. Sample Input:
10203040
Sample Output:
Number of zeros = 4

In [40]:
def zeros(n):
    if n == 0:
        return 0
    if n % 10 == 0:
        return 1 + zeros(n // 10)
    else:
        return zeros(n // 10)

num = int(input("Enter a number: "))
if num == 0:
    numzero= 1
else:
    numzero = zeros(num)

print("Number of zeros =", numzero)


Number of zeros = 1


5. List
Given a list of integers, rotate the list to the right by k positions and then find the longest increasing contiguous subsequence. Sample Input:
List = [5, 1, 3, 4, 2]
k = 2
Sample Output:
Rotated List: [4, 2, 5, 1, 3]
Longest Increasing Subsequence: [1, 3]

Given a sentence, reverse each word individually but keep the word order same. Ignore punctuation
marks. Sample Input:
Python is powerful!
Sample Output:
nohtyP si lufrewop

In [41]:
sentence = input("Enter the sentence: ")
rev_words = []

for i in sentence.split(" "):
    rev_words.append(i[::-1])

rev = " ".join(rev_words)
print(rev)


nohtyP si lufrewop


In [43]:
lst = [8,4,6,7,4,4,9,10]
k = 2

n = len(lst)
k = k % n

rotated = lst[-k:] + lst[:-k]
print("Rotated List:", rotated)

max_seq = []
current = [rotated[0]]

for i in range(1, n):
    if rotated[i] > rotated[i - 1]:
        current.append(rotated[i])
    else:
        if len(current) > len(max_seq):
            max_seq = current
        current = [rotated[i]]

if len(current) > len(max_seq):
    max_seq = current

print("Longest Increasing Subsequence:", max_seq)


Rotated List: [9, 10, 8, 4, 6, 7, 4, 4]
Longest Increasing Subsequence: [4, 6, 7]


In [30]:
marks = {}

n = int(input("Enter number of students: "))

for _ in range(n):
    name = input("Enter name: ")
    score = float(input("Enter marks: "))
    marks[name] = score

avg = sum(marks.values()) / len(marks)

for name in marks:
    if marks[name] < avg:
        marks[name] += marks[name] * 0.05

print(marks)


{'Amit': 70.0, 'Rina': 47.25, 'Suman': 63.0, 'Neha': 80.0}


In [29]:
import numpy as np

matrix = np.random.rand(5, 5)
print("Random 5x5 Matrix:")
print(matrix)

mean_value = matrix.mean()

binary_matrix = np.where(matrix > mean_value, 1, 0)

print("\nBinary Matrix based on Mean:")
print(binary_matrix)


Random 5x5 Matrix:
[[0.29646299 0.00659465 0.21309397 0.03790225 0.43011487]
 [0.0868368  0.24726693 0.42709976 0.15776863 0.08088574]
 [0.24628612 0.76355437 0.95731384 0.45867871 0.4423233 ]
 [0.07154258 0.16975624 0.24627101 0.4631393  0.45089831]
 [0.98454068 0.62667029 0.48667827 0.53428934 0.41472774]]

Binary Matrix based on Mean:
[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 1 1 1]
 [0 0 0 1 1]
 [1 1 1 1 1]]


In [32]:
import pandas as pd

data = {}
n = int(input("Enter number of students: "))

names = []
attendance = []

for _ in range(n):
    name = input("Enter name: ")
    att = int(input("Enter attendance: "))
    names.append(name)
    attendance.append(att)

data['Name'] = names
data['Attendance'] = attendance

df = pd.DataFrame(data)

df['Status'] = df['Attendance'].apply(lambda x: 'Eligible' if x >= 75 else 'Not Eligible')

eligible_count = (df['Status'] == 'Eligible').sum()

print(df)
print("Eligible Students Count:", eligible_count)


     Name  Attendance        Status
0    Jain          80      Eligible
1    Uday          45  Not Eligible
2  Ishika          46  Not Eligible
3   Karan          92      Eligible
Eligible Students Count: 2


In [37]:
import csv

data = """Product,Sales
Pen,200
Pen,350
Pencil,230
Pencil,504
"""

lines = data.split('\n')

with open('sales.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    for line in lines:
        writer.writerow(line.split(','))

print("CSV file 'sales.csv' created successfully!")

import pandas as pd

df = pd.read_csv("sales.csv")

df['Growth'] = df.groupby('Product')['Sales'].diff()

maxgrowth = df.loc[df['Growth'].idxmax()]

print("Highest Growth Product:", maxgrowth['Product'])



CSV file 'sales.csv' created successfully!
Highest Growth Product: Pencil
