In [2]:
import numpy as np
import pandas as pd

In [3]:
arr1 = np.arange(12,24)
arr2 = np.arange(12,24).reshape(3,4)

In [4]:
arr2**2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [5]:
arr2<18

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [6]:
a1 = np.arange(1,13).reshape(3,4)

In [7]:
a1*arr2

array([[ 12,  26,  42,  60],
       [ 80, 102, 126, 152],
       [180, 210, 242, 276]])

# Max/min/sum/prod

In [8]:
np.max(arr2)

np.int64(23)

In [9]:
np.sum(a1)

np.int64(78)

In [10]:
np.prod(a1)

np.int64(479001600)

In [11]:
np.min(arr1)

np.int64(12)

In [12]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
#min of the each row
#0->column
#1->row
np.min(arr2,axis=1)

array([12, 16, 20])

In [14]:
a1 = np.arange(1,21).reshape(4,5)
a2 = np.arange(2,22).reshape(5,4)

In [15]:
# dot product
np.dot(a2,a1)

array([[ 144,  158,  172,  186,  200],
       [ 280,  310,  340,  370,  400],
       [ 416,  462,  508,  554,  600],
       [ 552,  614,  676,  738,  800],
       [ 688,  766,  844,  922, 1000]])

In [16]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
arr2[1,3]

np.int64(19)

In [18]:
arr1[2:6:1]

array([14, 15, 16, 17])

In [19]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
arr2[0,:]
# pehla row saare columns

array([12, 13, 14, 15])

In [21]:
arr2[:,2]
# tisra column saare rows

array([14, 18, 22])

In [22]:
arr2[1:,1:3]

array([[17, 18],
       [21, 22]])

In [23]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
arr2[::2,::3]

array([[12, 15],
       [20, 23]])

In [25]:
arr2[::2,1::2]

array([[13, 15],
       [21, 23]])

In [26]:
arr2[1,::3]

array([16, 19])

In [27]:
arr2[0:2,1:]

array([[13, 14, 15],
       [17, 18, 19]])

In [28]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
arr2[[0,2]]

array([[12, 13, 14, 15],
       [20, 21, 22, 23]])

In [31]:
arr2[:,[1,2]]

array([[13, 14],
       [17, 18],
       [21, 22]])

In [33]:
#Boolean Indexing

ar = np.random.randint(1,100,24).reshape(6,4)
print(ar)

[[45 12 78 88]
 [83 84 62 31]
 [68 72  4 71]
 [32 37 35 47]
 [40 55 60 80]
 [23 81 61 13]]


In [35]:
ar[ar>50]

array([78, 88, 83, 84, 62, 68, 72, 71, 55, 60, 80, 81, 61], dtype=int32)

In [ ]:
ar[ar%2==0]

array([12, 78, 88, 84, 62, 68, 72,  4, 32, 40, 60, 80], dtype=int32)

In [41]:
ar[(ar%2==0) & (ar>50)]

array([78, 88, 84, 62, 68, 72, 60, 80], dtype=int32)

In [43]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
def sigmoid(num):
    return 1/(1+np.exp(-(num)))

sigmoid(arr)

# arr.apply(sigmoid)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715,
       0.99752738, 0.99908895, 0.99966465, 0.99987661])

# numpy functions

In [52]:
ar = np.random.randint(1,20,20)
ar

array([ 1,  8, 17,  8,  5,  8,  3,  5, 11,  3,  3, 12,  5, 13,  2,  3, 15,
        6, 19,  6], dtype=int32)

In [ ]:
np.sort(ar)

array([ 1,  2,  3,  3,  3,  3,  5,  5,  5,  6,  6,  8,  8,  8, 11, 12, 13,
       15, 17, 19], dtype=int32)

In [55]:
np.append(ar,13)

array([ 1,  8, 17,  8,  5,  8,  3,  5, 11,  3,  3, 12,  5, 13,  2,  3, 15,
        6, 19,  6, 13])

In [57]:
mat = np.random.randint(1,50,20).reshape(4,5)
mat

array([[21, 21, 32, 35, 38],
       [25,  5,  6, 29,  1],
       [ 1, 40, 25, 44, 19],
       [32, 37, 42, 28,  2]], dtype=int32)

In [ ]:
np.sort(mat,axis=1) # rowwise

array([[21, 21, 32, 35, 38],
       [ 1,  5,  6, 25, 29],
       [ 1, 19, 25, 40, 44],
       [ 2, 28, 32, 37, 42]], dtype=int32)

In [59]:
np.sort(mat,axis=0)

array([[ 1,  5,  6, 28,  1],
       [21, 21, 25, 29,  2],
       [25, 37, 32, 35, 19],
       [32, 40, 42, 44, 38]], dtype=int32)

In [60]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[np.where(arr>5)]

array([6, 7, 8, 9])

In [66]:
np.where(arr%2==0,0,arr)

array([1, 0, 3, 0, 5, 0, 7, 0, 9])