Submitted by :- 
Name - Omm Tripathi | 
Roll No - 23051606 | 
Section - CSE-35 | 
Lab - CW-FAC-TA EVALUATION |
Set - 1

----------------------------------------------------------------------------------------------

1. [Assignment 0.1 - Python Basics]
Write a Python program to input weight in grams and
convert it into kilograms and grams.

Sample Input:

Enter weight in grams: 3456

Sample Output:

3 Kilograms and 456 Grams

In [5]:
wt = int(input("enter the weight in Grams"))
print("Weight enetered in grams:",wt)
kilo = wt//1000
wt= wt%1000
print(kilo,"kilograms and",wt,"grams")

Weight enetered in grams: 3456
3 kilograms and 456 grams


----------------------------------------------------------------------------------------------

2. [Assignment 0.2 - Control Structures]
Write a Python program to print a diamond pattern using
alphabets. Accept number of rows from user (maximum 5).

Sample Input:

Enter number of rows (max 5): 3

Sample Output:

A
B B
C C C
B B
A

In [7]:
rows = int(input("enter number of rows(max 5): "))

for i in range(rows):
    for s in range(rows - i - 1):
        print(" ", end="")
    ch = chr(65 + i)
    for j in range(i + 1):
        print(ch, end=" ")
    print()

for i in range(rows - 2, -1, -1):
    for s in range(rows - i - 1):
        print(" ", end="")
    ch = chr(65 + i)
    for j in range(i + 1):
        print(ch, end=" ")
    print()



  A 
 B B 
C C C 
 B B 
  A 


----------------------------------------------------------------------------------------------

3. [Assignment 0.3 - Functions]
Write a recursive function to find the product of numbers
from 1 to n, but skip every third number.

For example: for n=5, calculate 1 × 2 × 4 × 5

Sample Input:

Enter n: 5

Sample Output:

Numbers used: 1, 2, 4, 5

Skipped numbers: 3

Result: 40

In [11]:
n = int(input("Enter the number for multiplication"))
used = []
skipped = []
def recurr(n,result):
    if(n==0):
        return result
    if(n%3==0):
        skipped.append(n)
        return recurr(n-1,result)
    used.append(n)
    return recurr(n-1,result*n)

ans = recurr(n,1)
print("Result:",ans)
print("Numbers used:",used[::-1])
print("Numbers skipped",skipped)


Result: 40
Numbers used: [1, 2, 4, 5]
Numbers skipped [6, 3]


------------------------------------------------------------------------------------------------

4. [Assignment 0.4 - Data Structures in Python]

Create a program to manage a contact list using dictionary.Each contact should have name, phone numbers (multiple),email, and category (family/friend/work). Include functions
to:
- Add new contact
- Add additional phone number to existing contact
- Search by name or phone number
- Display contacts by category
Sample Input:
1. Add Contact
- Enter Name: Rahul Kumar
- Enter Primary Phone: 9876543210
- Enter Additional Phone (or press enter to skip): 8765432109
- Enter Email: rahul@email.com
- Enter Category (family/friend/work): family
2. Search Contact
- Enter search term: 9876543210
- Sample Output:
- Contact Added Successfully:
- Name: Rahul Kumar
- Phones: [9876543210, 8765432109]

In [34]:
contacts = {}

def add_contact():
    name = input("enter name: ")
    prim =input("enter primary phone: ")
    addi =input("enter additional phone (or press enter to skip): ")
    phones = [prim]
    if addi != "":
        phones.append(addi)
    
    email = input("enter email: ")
    category = input("enter Category (family/friend/work): ")
    
    contacts[name] = {
        "phones": phones,
        "email": email,
        "category": category
    }
    print("Contact Added Successfully!")

def add_phone():
    name = input("enter contact name to add phone: ")
    if name in contacts:
        new_phone = input("enter new phone number: ")
        contacts[name]["phones"].append(new_phone)
        print("phone number added.")
    else:
        print("not found")

def search_contact():
    term = input("enter search term (name or phone): ")
    found = False
    for name, info in contacts.items():
        if term == name or term in info["phones"]:
            print("name:", name)
            print("phones:", info["phones"])
            print("email:", info["email"])
            print("category:", info["category"])
            found = True
    if not found:
        print("no contct found")

def display_by_category():
    cat = input("Enter category to display (family/friend/work): ")
    for name, info in contacts.items():
        if info["category"].lower() == cat.lower():
            print("Name:", name)
            print("Phones:", info["phones"])
            print("Email:", info["email"])
            print("Category:", info["category"])
            print("-------------------------")
            
while True:
    print("\nContact Menu:")
    print("1. Add Contact")
    print("2. Add Additional Phone")
    print("3. Search Contact")
    print("4. Display Contacts by Category")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_contact()
    elif choice == "2":
        add_phone()
    elif choice == "3":
        search_contact()
    elif choice == "4":
        display_by_category()
    elif choice == "5":
        print("exit")
        break
    else:
        print("wrong choice")
        
print(contacts)



Contact Menu:
1. Add Contact
2. Add Additional Phone
3. Search Contact
4. Display Contacts by Category
5. Exit
Contact Added Successfully!

Contact Menu:
1. Add Contact
2. Add Additional Phone
3. Search Contact
4. Display Contacts by Category
5. Exit
Contact Added Successfully!

Contact Menu:
1. Add Contact
2. Add Additional Phone
3. Search Contact
4. Display Contacts by Category
5. Exit
Contact Added Successfully!

Contact Menu:
1. Add Contact
2. Add Additional Phone
3. Search Contact
4. Display Contacts by Category
5. Exit

Contact Menu:
1. Add Contact
2. Add Additional Phone
3. Search Contact
4. Display Contacts by Category
5. Exit
name: lavanya
phones: ['9876875745']
email: kumari@gmail.com
category: work

Contact Menu:
1. Add Contact
2. Add Additional Phone
3. Search Contact
4. Display Contacts by Category
5. Exit
exit
{'Rahul': {'phones': ['989787976', '876879789'], 'email': 'h@gmail.com', 'category': 'family'}, 'kumar': {'phones': ['98763674875', '987857683'], 'email': 'k@email

-----------------------------------------------------------------------------------------------

5. [Assignment 0.5 - NumPy]
Using NumPy, create a program that:
- Creates a 5×5 checkerboard pattern matrix with 1s and 0s
- Rotates it 45 degrees
- Calculates the sum of elements in each quadrant
- Finds the coordinates of all 1s in the rotated matrix

Sample Output:
[[1 0 1 0 1]

[0 1 0 1 0]

[1 0 1 0 1]

[0 1 0 1 0]

[1 0 1 0 1]]

Rotated Matrix:
[[0 0 1 0 0]

[0 1 0 1 0]

[1 0 1 0 1]

[0 1 0 1 0]

[0 0 1 0 0]]

Quadrant Sums:

Top-Left: 2

Top-Right: 2

Bottom-Left: 2

Bottom-Right: 2

Coordinates of 1s:

[(0,2), (1,1), (1,3), (2,0), (2,2), (2,4), (3,1), (3,3), (4,2)]

In [51]:
import numpy as np 
# rotation
def rotate_45(mat):
    N = len(mat)
    rotated = [[0]*N for _ in range(N)]

    for i in range(N):
        for j in range(N):
            new_i = i + j - N//2
            new_j = abs(i - j)
            if 0 <= new_i < N and 0 <= new_j < N:
                rotated[new_i][new_j] = int(mat[i][j])
    
    return rotated

def quadrant_sums(rotated):
    size = len(rotated)
    mid = size // 2
    tl = tr = bl = br = 0
    
    for i in range(size):
        for j in range(size):
            val = rotated[i][j]
            if i < mid and j < mid:
                tl += val
            elif i < mid and j > mid:
                tr += val
            elif i > mid and j < mid:
                bl += val
            elif i > mid and j > mid:
                br += val
    return tl, tr, bl, br

def coordinates_of_ones(rotated):
    coords = []
    for i in range(len(rotated)):
        for j in range(len(rotated)):
            if rotated[i][j] == 1:
                coords.append((i,j))
    return coords

matrix = np.array([
    [1,0,1,0,1],
    [0,1,0,1,0],
    [1,0,1,0,1],
    [0,1,0,1,0],
    [1,0,1,0,1]
])

rotated = rotate_45(matrix)

print("Rotated Matrix:")
for row in rotated:
    print(row)

tl, tr, bl, br = quadrant_sums(rotated)
print("\nQuadrant Sums:")
print("Top-Left:", tl)
print("Top-Right:", tr)
print("Bottom-Left:", bl)
print("Bottom-Right:", br)

ones_coords = coordinates_of_ones(rotated)
print("\nCoordinates of 1s:", ones_coords)


Rotated Matrix:
[1, 0, 1, 0, 0]
[0, 0, 0, 0, 0]
[1, 0, 1, 0, 1]
[0, 0, 0, 0, 0]
[1, 0, 1, 0, 0]

Quadrant Sums:
Top-Left: 1
Top-Right: 0
Bottom-Left: 1
Bottom-Right: 0

Coordinates of 1s: [(0, 0), (0, 2), (2, 0), (2, 2), (2, 4), (4, 0), (4, 2)]


-----------------------------------------------------------------------------------------------

6. [Assignment 0.6 - Pandas]

Create a DataFrame to analyze monthly expense data with
categories (Food, Transport, Utilities, Entertainment,
Others). Write program to:
- Calculate percentage distribution of expenses
- Compare month-over-month changes
- Identify top 3 expense categories
- Generate monthly budget report

Sample Input:
Enter expenses for 3 months:

Month 1:

Food: 8000

Transport: 3000
Utilities: 4500
Entertainment: 2500
Others: 2000

Sample Output:
Expense Distribution (Latest Month):

Food: 40%

Transport: 15%

Utilities: 22.5%

Entertainment: 12.5%

Others: 10%

Month-over-Month Changes:

Food: +5%

Transport: -2%

Top Expense Categories:

1. Food (₹24,500)

2. Utilities (₹13,500)

3. Transport (₹9,000)

Budget Summary:

Total Monthly Average: ₹20,000

Highest Expense Month: Month 1

Lowest Expense Month: Month 3

Suggested Savings: ₹5,000


In [42]:
import pandas as pd

months = int(input("Enter number of months: "))
categories = ["Food", "Transport", "Utilities", "Entertainment", "Others"]

data = {}
for i in range(1, months + 1):
    expenses = []
    for cat in categories:
        amount = float(input("enter amount for catergory"))
        expenses.append(amount)
    data[i] = expenses

df = pd.DataFrame(data, index=categories)
print("\nExpense DataFrame:")
print(df)

latest_expense = df[months]
distribution = (latest_expense / latest_expense.sum()) * 100

print("\nexpense distribution (Latest Month):")
for cat, perc in distribution.items():
    print(f"{cat}: {perc:.1f}%")
    
    
print("\nmonth-over-month changes:")
if months > 1:
    for i in range(1, months):
        prev = i
        curr =i+1 
        changes = df[curr] - df[prev]
        for cat in categories:
            change = changes[cat]
            if change > 0:
                print(f"{cat} ({curr} vs {prev}): +{change}")
            elif change < 0:
                print(f"{cat} ({curr} vs {prev}): {change}")
            else:
                print(f"{cat} ({curr} vs {prev}): No change")
                
print("\n top expense category")
total = df.sum(axis=1).sort_values(ascending=False)
top3 = total.head(3)
for i in range(3):
    cat = top3.index[i]
    amount = top3.iloc[i]
    print(f"{i+1}. {cat} (₹{amount:.0f})")

    

monthly = df.sum()
avg = monthly.mean()
highest = monthly.idxmax()
lowest = monthly.idxmin()
suggested = avg * 0.10

print("\nBudget Summary:")
print("Total Monthly Average: ₹",avg)
print("Highest Expense Month: ",highest)
print("Lowest Expense Month:",lowest)
print("Suggested Savings: ₹",suggested)



Expense DataFrame:
                    1       2
Food           8000.0  8000.0
Transport      7000.0  5000.0
Utilities      6000.0  6000.0
Entertainment  5000.0  4000.0
Others         1200.0  1200.0

expense distribution (Latest Month):
Food: 33.1%
Transport: 20.7%
Utilities: 24.8%
Entertainment: 16.5%
Others: 5.0%

month-over-month changes:
Food (2 vs 1): No change
Transport (2 vs 1): -2000.0
Utilities (2 vs 1): No change
Entertainment (2 vs 1): -1000.0
Others (2 vs 1): No change

 top expense category
1. Food (₹16000)
2. Transport (₹12000)
3. Utilities (₹12000)

Budget Summary:
Total Monthly Average: ₹ 25700.0
Highest Expense Month:  1
Lowest Expense Month: 2
Suggested Savings: ₹ 2570.0
