Submitted by :- 
Name - Omm Tripathi | 
Roll No - 23051606 | 
Section - CSE-35 | 
Lab - 1 |
Assignment- 0.5

-----------------------------------------------------------------------------------------------

In [2]:
import numpy as np

0.5.1. Write a program to create a null vector of size 25 but the values from fifth to tenth elements are all 1.

In [ ]:
arr1 = np.zeros(25)
arr1[5:11] = 1
print(arr1)


[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


-----------------------------------------------------------------------------------------------

0.5.2. Write a program to create a vector with values ranging from 5 to 20 & reverse it

In [13]:
arr1 = np.arange(5,21)
print("Original:",arr1)
arr1 =  arr1[::-1]
print("Reversed:",arr1)

Original: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reversed: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]


-----------------------------------------------------------------------------------------------

0.5.3. Write a program to create a vector with 10 random values & sort first half ascending & second half descending.

In [3]:
arr1 = np.array(np.random.randint(0,100,10))
print("Arr1:",arr1)
arr1[0:5] = np.sort(arr1[0:5])
arr1[5:10] = np.sort(arr1[5:10])[::-1]
print("Sorted:",arr1)

Arr1: [95 71 81 83  0 58 28  7 32 96]
Sorted: [ 0 71 81 83 95 96 58 32 28  7]


-----------------------------------------------------------------------------------------------

0.5.4. Write a program to create a vector of size 10 with values ranging from 0 to 1, both excluded.  

In [29]:
arr1 = np.linspace(0.1,0.9999,11)
print(arr1)

[0.1     0.18999 0.27998 0.36997 0.45996 0.54995 0.63994 0.72993 0.81992
 0.90991 0.9999 ]


-----------------------------------------------------------------------------------------------

0.5.5. Write a program to concatenate element-wise two arrays of string.

In [88]:
arr1 = np.array(["this","is","concat","of arr1"])
arr2 = np.array(["code","a","product"," and arr2"])
arr3 = np.char.add(arr1,arr2) 
print(arr3)

['thiscode' 'isa' 'concatproduct' 'of arr1 and arr2']


-----------------------------------------------------------------------------------------------

0.5.6. Write a program to create a 4x3 array with random values & find out the minimum & maximum values

In [47]:
arr1 = np.array(np.random.randint(0,100,12))
grid = arr1.reshape(4,3)
print(grid)
print("Maximum element:",grid.max())
print("Minimum element:",grid.min())

[[78 74 44]
 [55 14 24]
 [33 54 28]
 [17 72  8]]
Maximum element: 78
Minimum element: 8


-----------------------------------------------------------------------------------------------

0.5.7. Write a program to create a 2D array with 1 on the border and 0 inside.  

In [54]:
arr1  = np.zeros(20)
grid = arr1.reshape(4,5)
for i in range(4):
    for j in range(5):
        if(i==0 or j==0 or i==3 or j==4):
            grid[i][j] = 1
            
print(grid)
            

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


-----------------------------------------------------------------------------------------------

0.5.8. Write a program to create a 4x4 matrix with values 1,2,3,4 just below & above the diagonal, rest zeros.

In [ ]:
# grid = np.zeros((4,4),dtype=int)
# below diagonal
# j = 0
# for i in range(1,4):
#     grid[i][j] = 1
#     j+=1
    
# # upper diag
# i=0
# for j in range(1,4):
#     grid[i][j] = 2
#     i+=1
    
# print(grid)


# numpy code
mat = np.zeros((4, 4), dtype=int)
mat += np.diag([1, 1, 1], k=-1)
mat += np.diag([2, 2, 2], k=1) 
print(mat)
    
    

[[0 2 0 0]
 [1 0 2 0]
 [0 1 0 2]
 [0 0 1 0]]


-----------------------------------------------------------------------------------------------

0.5.9. Write a program to extract all the contiguous 3x3 blocks from a random 10x10 matrix. 

In [90]:
import numpy as np

matrix = np.random.randint(0, 10, size=(10, 10))
print(matrix)
blocks = []

for i in range(8):
    for j in range(8):
        blocks.append(matrix[i:i+3, j:j+3])

count = 1
for blk in blocks:
    print("Block", count, ":\n", blk)
    count += 1


[[2 9 5 5 5 7 2 1 7 1]
 [2 1 1 0 8 3 2 3 7 2]
 [4 2 6 7 5 0 9 1 9 4]
 [8 4 2 1 9 9 6 4 6 0]
 [5 2 3 1 5 9 8 4 7 6]
 [5 0 9 5 2 1 1 5 4 9]
 [9 0 3 3 3 6 1 2 8 9]
 [1 8 4 1 8 2 3 0 5 3]
 [0 7 7 3 0 4 7 7 8 5]
 [5 3 7 6 1 8 6 5 9 4]]
Block 1 :
 [[2 9 5]
 [2 1 1]
 [4 2 6]]
Block 2 :
 [[9 5 5]
 [1 1 0]
 [2 6 7]]
Block 3 :
 [[5 5 5]
 [1 0 8]
 [6 7 5]]
Block 4 :
 [[5 5 7]
 [0 8 3]
 [7 5 0]]
Block 5 :
 [[5 7 2]
 [8 3 2]
 [5 0 9]]
Block 6 :
 [[7 2 1]
 [3 2 3]
 [0 9 1]]
Block 7 :
 [[2 1 7]
 [2 3 7]
 [9 1 9]]
Block 8 :
 [[1 7 1]
 [3 7 2]
 [1 9 4]]
Block 9 :
 [[2 1 1]
 [4 2 6]
 [8 4 2]]
Block 10 :
 [[1 1 0]
 [2 6 7]
 [4 2 1]]
Block 11 :
 [[1 0 8]
 [6 7 5]
 [2 1 9]]
Block 12 :
 [[0 8 3]
 [7 5 0]
 [1 9 9]]
Block 13 :
 [[8 3 2]
 [5 0 9]
 [9 9 6]]
Block 14 :
 [[3 2 3]
 [0 9 1]
 [9 6 4]]
Block 15 :
 [[2 3 7]
 [9 1 9]
 [6 4 6]]
Block 16 :
 [[3 7 2]
 [1 9 4]
 [4 6 0]]
Block 17 :
 [[4 2 6]
 [8 4 2]
 [5 2 3]]
Block 18 :
 [[2 6 7]
 [4 2 1]
 [2 3 1]]
Block 19 :
 [[6 7 5]
 [2 1 9]
 [3 1 5]]
Block 20 :
 [[7 5 

-----------------------------------------------------------------------------------------------

0.5.10. A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are
the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes
from top right to bottom left.) Show by direct computation that if the matrix A is given by


A=np.array([[17, 24, 1, 8, 15],
            [23, 5, 7, 14, 16],
            [ 4, 6, 13, 20, 22],
            [10, 12, 19, 21, 3], 
            [11, 18, 25, 2, 9]])

The matrix A has 5 row sums (one for each row), 5 column sums (one for each column) and two
diagonal sums. These 12 sums should all be exactly the same, and you could verify that they are the
same by printing them and “seeing” that they are the same. It is easy to miss small differences among so
many numbers, though. Instead, verify that A is a magic square by constructing the 5 column sums and
computing the maximum and minimum values of the column sums. Do the same for the 5 row sums, and compute the two diagonal sums. Check that these six values are the same. If the maximum and
minimum values are the same, the flyswatter principle says that all values are the same.

In [79]:
mat=np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [ 4, 6, 13, 20, 22], [10, 12, 19, 21, 3]])
print(mat)
list1=[]
list1.append(np.sum(np.diag(mat, k=1)))

list1.append(np.sum(np.diag(np.fliplr(mat))))

col = np.sum(mat, axis=0)
list1.extend(col)

row = np.sum(mat, axis=1)
list1.extend(row)

flag = True
for i in range(len(list1)-1):
    if(list1[i] != list1[i+1]):
        flag = False

if(flag==True):
    print("Magic Square")
else:
    print("Not a Magic Square")

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]]
Not a Magic Square
